# Turn off the display
listener {
    timeout = 180
    on-timeout = playerctl status | grep -q Playing || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Sleep if its on battery
listener {
    timeout = 600
    on-timeout = [ $(cat /sys/class/power_supply/AC0/online) -eq 0 ] && systemctl suspend
}