general {
    after_sleep_cmd = ~/.config/scripts/system/on-suspend.sh
}
    
# Turn off the display
listener {
    timeout = 180
    on-timeout = [ $(playerctl status 2>/dev/null) = "Playing" ] || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Sleep if its on battery
listener {
    timeout = 600
    on-timeout = [ $(cat "$(grep -l "Mains" /sys/class/power_supply/*/type | sed 's|/type||')/online") -eq 0 ] && systemctl suspend
}
