source = ~/.cache/wal/colors-hyprland.conf

general {
  fractional_scaling = 2
  ignore_empty_input = true
  animation = fade_in 0.2
}

animation {
  fade_in = 0.2
}

background {
    monitor =
    path = $HOME/.local/share/assets/lockscreens/lockscreen.jpg
    blur_passes = 2
}

input-field {
  monitor =
  size = 200, 40
  outline_thickness = 0
  placeholder_text = <i>Enter password</i>
  always_show = true
  fade_on_empty = false
  outer_color = $color14 color13 45deg
  inner_color = $color0
  font_color = $color14
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$TIME"
    font_size = 60
    position = -100, 70
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    #clock
    text = cmd[update:1000] echo "$(date +"%A, %B %d %Y")"
    font_size = 18
    position = -100, 50
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    text = $USER
    font_size = 30
    shadow_passes = 5
    shadow_size = 10
    position = 0, 60
}