# This is the source of anything related to laptop monitor scripts, you can (and should) change this according to your setup,
# The monitors in /hyprconfig/monitors.conf will be replaced by these values

monitor=HDMI-A-1,preferred,auto,1
monitor=eDP-1,preferred,auto,1.5