# This is the source of anything related to laptop monitor scripts, you can (and should) change this according to your setup.
# The laptop monitor in monitors.conf will be replaced by these values everytime the pc boots, changing themes,
# or closing / opening laptop lid.

monitor=HDMI-A-1,preferred,auto,auto
monitor=eDP-1,preferred,auto,1.5

