# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $HOME/.config/scripts/system/startup.sh
exec-once = udisksctl mount -b /dev/nvme0n1p3 && udisksctl mount -b /dev/nvme0n1p5
exec-once = $HOME/.config/scripts/limit-tdp.sh
exec-once = hypridle
