# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Custom window rule
windowrule = opacity 0.90 0.90, class:^(code|thunar|discord|steam|mousepad)$
windowrule = opacity 0.90 0.90, class:.*chrome-(chatgpt|netflix|canary\.discord|open\.spotify|web\.whatsapp|web\.telegram).*

# Hide windows with "hidden" in the title
windowrule = opacity 0 0, title:^(hidden)$
windowrule = noblur, title:^(hidden)$

# Floating windows
windowrule = float,title:.*(Open File|Open Folder|Open|Save|Save As|Export|Import|Choose File|Rename|Copy|Move|Replace|File Operation Progress).*, class:^(.*)$
windowrule = float,class:^(org.gnome.Calculator|org.gnome.eog|org.pulseaudio.pavucontrol)$

# Floatin window size
windowrule = size 800 600,title:.*(Open File|Open Folder|Open|Save|Save As|Export|Import|Choose File|Rename|Copy|Move|Replace|File Operation Progress).*, class:^(.*)$
windowrule = size 800 600,class:^(org.gnome.Calculator|org.gnome.eog|org.pulseaudio.pavucontrol)$

# Stay focused window
windowrule = stayfocused,title:.*(Open File|Open Folder|Open|Save|Save As|Export|Import|Choose File|Rename|Copy|Move|Replace).*, class:^(.*)$
windowrule = stayfocused,class:^(org.pulseaudio.pavucontrol)$

# Tiling windows
windowrule = tile, class:^(scrcpy)$

# Bluetoothctl terminal
windowrule = workspace special:hidden silent, title:^(bluetoothctl)$

# Screen sharing window rule on xwayland
windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$
