# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Custom window rule by Fariz
windowrule = opacity 0.95 0.95, class:^(code)$
windowrule = opacity 0.90 0.90, class:^(thunar)$
windowrule = opacity 0.90 0.90, class:^(discord)$
windowrule = opacity 0.95 0.95, class:^(steam)$

# Hide windows with "hidden" in the title
windowrule = opacity 0 0, title:^(hidden)$
windowrule = noblur, title:^(hidden)$

# Floating windows
windowrule = float,class:^(org.gnome.Calculator)$

windowrule = float,class:^(org.kde.gwenview)$
windowrule = size 1000 800, class:^(?i)org.kde.gwenview$

windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = stayfocused,class:^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600, class:^(?i)org.pulseaudio.pavucontrol$