# Shell variables
# Generated by 'wal'
wallpaper='/home/fariz/.local/share/assets/wallpapers/wallpaper07.jpg'

# Special
background='#010D15'
foreground='#88c0d8'
cursor='#88c0d8'

# Colors
color0='#010D15'
color1='#0F627C'
color2='#405169'
color3='#08548B'
color4='#106994'
color5='#0D6FAC'
color6='#2E76B3'
color7='#88c0d8'
color8='#5f8697'
color9='#0F627C'
color10='#405169'
color11='#08548B'
color12='#106994'
color13='#0D6FAC'
color14='#2E76B3'
color15='#88c0d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
