--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fariz/.local/share/assets/wallpapers/wallpaper07.jpg"

-- Special
background="#010D15"
foreground="#88c0d8"
cursor="#88c0d8"

-- Colors
color0="#010D15"
color1="#0F627C"
color2="#405169"
color3="#08548B"
color4="#106994"
color5="#0D6FAC"
color6="#2E76B3"
color7="#88c0d8"
color8="#5f8697"
color9="#0F627C"
color10="#405169"
color11="#08548B"
color12="#106994"
color13="#0D6FAC"
color14="#2E76B3"
color15="#88c0d8"
