return {
  -- {
  --   "folke/tokyonight.nvim",
  --   opts = {
  --     transparent = true,
  --     styles = {
  --       sidebars = "transparent",
  --       floats = "transparent",
  --     },
  --     on_colors = function(colors)
  --       colors.bg_dark = "NONE"
  --       colors.bg_dark1 = "#191B29"
  --       colors.bg_float = "NONE"
  --       colors.bg_highlight = "#2f334d"
  --       colors.bg_popup = "#1e2030"
  --       colors.bg_search = "#3e68d7"
  --       colors.bg_sidebar = "NONE"
  --       colors.bg_statusline = "NONE"
  --       colors.bg_visual = "#404040"
  --       colors.black = "#1b1d2b"
  --       colors.blue = "#82aaff"
  --       colors.blue0 = "#3e68d7"
  --       colors.blue1 = "#65bcff"
  --       colors.blue2 = "#0db9d7"
  --       colors.blue5 = "#89ddff"
  --       colors.blue6 = "#b4f9f8"
  --       colors.blue7 = "#394b70"
  --       colors.border = "#1b1d2b"
  --       colors.border_highlight = "#589ed7"
  --       colors.comment = "#636da6"
  --       colors.cyan = "#86e1fc"
  --       colors.dark3 = "#545c7e"
  --       colors.dark5 = "#737aa2"
  --       colors.error = "#c53b53"
  --       colors.fg = "#c8d3f5"
  --       colors.fg_dark = "#828bb8"
  --       colors.fg_float = "#c8d3f5"
  --       colors.fg_gutter = "#404040"
  --       colors.fg_sidebar = "#828bb8"
  --       colors.green = "#c3e88d"
  --       colors.green1 = "#4fd6be"
  --       colors.green2 = "#41a6b5"
  --       colors.hint = "#4fd6be"
  --       colors.info = "#0db9d7"
  --       colors.magenta = "#c099ff"
  --       colors.magenta2 = "#ff007c"
  --       colors.none = "NONE"
  --       colors.orange = "#ff966c"
  --       colors.purple = "#fca7ea"
  --       colors.red = "#ff757f"
  --       colors.red1 = "#c53b53"
  --       colors.teal = "#4fd6be"
  --       colors.terminal_black = "#444a73"
  --       colors.todo = "#82aaff"
  --       colors.warning = "#ffc777"
  --       colors.yellow = "#ffc777"
  --     end,
  --   },
  -- },
}

