general.import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
opacity = 0.85

[window.padding]
y = 10
x = 10

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "bold" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
